---
title: "New Class Enrollment"
author: "Stephanie Cheng"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(janitor)
library(gt)
```

```{r}
url_current <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.25.20_0.xlsx"

url_old <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19_0.xlsx"

download.file(url = url_current,
              destfile ="current.xlsx" )

download.file(url = url_old,
              destfile ="old.xlsx" )

current <- read_excel("current.xlsx", skip = 3) %>%
  clean_names() %>%
  filter(!is.na(course_name))

old <- read_excel("old.xlsx", skip = 3) %>%
  clean_names() %>%
  filter(!is.na(course_name))

top_5_new_courses <- anti_join(current, old, by = "course_id") %>%
  arrange(desc(total)) %>%
  select(course_name, course_department, total) %>%
  slice(1:5) %>%
  gt()
```
